### ISSUE TITLE
Use toggles for hiding leaves feature

### ISSUE THREAD

**Issue by dev-ritik** [mdg-iitr/appetizer-flutter#173]
We have added `/panel/toggle/<name>/` to the backend. This can be used to decide if the user will be able to mark leaves (and Checkouts)

**Comment by Nitish145** [comment]
This was implemented using `remote_config`'s `is_leave_enabled` & `is_switch_enabled`

Fixed in [e52123d](https://github.com/mdg-iitr/appetizer-flutter/commit/e52123d4ec1f4e213f12eda3ce9ed96b4ea625fe)
